charts part 2
elrick97/CodeU-T5 pull request #19
Opened 2019-03-18 23:16 UTC by mahiSha123

2019-03-18 23:34 UTC, tbiscuit commented on src/main/java/com/google/codeu/data/Datastore.java
> +    	if(recipient =="" || recipient == null) {
```suggestion
    	if(recipient == "" || recipient == null) {
```

2019-03-18 23:40 UTC, tbiscuit requested changes
Since this review is here, I believe I can safely assume you've solved the issue where git refused to see your changes. 👍 

If getting the auto-formatting working is troublesome let me know.

2019-03-18 23:40 UTC, tbiscuit commented on src/main/java/com/google/codeu/data/Datastore.java
> +    		Query query =
The spacing here seems non-idiomatic for Java. Should be consistently all spaces or all tabs, spaces are preferred with a typical indent of 2. Don't do it by hand though: https://github.com/google/google-java-format

2019-03-25 01:49 UTC, sophiagiordano approved these changes

2019-03-31 20:09 UTC, tbiscuit approved these changes

2019-04-01 00:32 UTC, merged