Step 2: Public Feed
elrick97/CodeU-T5 pull request #2
Opened 2019-02-19 21:41 UTC by elrick97

Hi guys, just creating this pull request to start familiarizing with this. This new portion of code includes the second step on the public feed. :) Have a great day!

2019-02-20 01:24 UTC, tbiscuit requested changes
Nice! Couple minor requests. :)

2019-02-20 01:24 UTC, tbiscuit commented on src/main/webapp/WEB-INF/appengine-web.xml
> +  <version>rick</version>
Should put this back to 1 before pulling. 
```suggestion
  <version>1</version>
```

2019-02-20 01:24 UTC, tbiscuit commented on target/codeu-starter-project-0.0.1-SNAPSHOT/WEB-INF/appengine-web.xml
> +  <version>rick</version>
```suggestion
  <version>1</version>
```

2019-02-22 00:03 UTC, elrick97 commented
Did the changes in my last commit. :)

2019-02-22 00:03 UTC, closed without merging